"use client";
import {useEffect,useMemo,useState} from "react";
import {ArrowRight,BarChart3,Bell,Check,CircleDollarSign,Clock3,CreditCard,Eye,Heart,LayoutDashboard,LockKeyhole,MessageSquareWarning,Minus,Package,Plus,Search,Settings,ShieldCheck,ShoppingBag,Store,Trash2,TrendingUp,Upload,UserRound,WalletCards} from "lucide-react";
import {Button} from "@/components/ui/button";import {Dialog,DialogContent,DialogDescription,DialogHeader,DialogTitle} from "@/components/ui/dialog";import {Input} from "@/components/ui/input";import {Label} from "@/components/ui/label";import {Progress} from "@/components/ui/progress";import {Sheet,SheetContent,SheetHeader,SheetTitle,SheetTrigger} from "@/components/ui/sheet";import {Tabs,TabsContent,TabsList,TabsTrigger} from "@/components/ui/tabs";import {Textarea} from "@/components/ui/textarea";import {Toaster,toast} from "sonner";
type P={id:number,name:string,cat:string,price:number,old?:number,rating:number,image:string,seller:string,badge?:string,stock:number};type C=P&{qty:number};
const ps:P[]=[
{id:1,name:"Auralis Studio Max",cat:"Audio",price:189000,old:225000,rating:4.9,image:"https://images.unsplash.com/photo-1505740420928-5e560c06d30e?auto=format&fit=crop&w=1200&q=88",seller:"SoundDistrict",badge:"Best seller",stock:16},
{id:2,name:"Forma Runner 02",cat:"Sneakers",price:96500,old:118000,rating:4.8,image:"https://images.unsplash.com/photo-1542291026-7eec264c27ff?auto=format&fit=crop&w=1200&q=88",seller:"Common Ground",badge:"New drop",stock:9},
{id:3,name:"Orbit Pro Watch",cat:"Tech",price:145000,rating:4.7,image:"https://images.unsplash.com/photo-1523275335684-37898b6baf30?auto=format&fit=crop&w=1200&q=88",seller:"Tekhouse",stock:22},
{id:4,name:"No. 12 Weekender",cat:"Bags",price:128000,old:149000,rating:4.9,image:"https://images.unsplash.com/photo-1553062407-98eeb64c6a62?auto=format&fit=crop&w=1200&q=88",seller:"Atelier Lagos",badge:"Limited",stock:4},
{id:5,name:"Arcline Mirrorless",cat:"Cameras",price:579000,rating:4.8,image:"https://images.unsplash.com/photo-1516035069371-29a1b244cc32?auto=format&fit=crop&w=1200&q=88",seller:"Frame Theory",stock:7},
{id:6,name:"Sora Lounge Chair",cat:"Home",price:214000,old:245000,rating:4.6,image:"https://images.unsplash.com/photo-1503602642458-232111445657?auto=format&fit=crop&w=1200&q=88",seller:"Soft Form",stock:12}];
const cash=(n:number)=>new Intl.NumberFormat("en-NG",{style:"currency",currency:"NGN",maximumFractionDigits:0}).format(n);
export default function Home(){const[mode,setMode]=useState<"shop"|"seller">("shop"),[cart,setCart]=useState<C[]>([]),[q,setQ]=useState(""),[cat,setCat]=useState("All"),[auth,setAuth]=useState(false),[bag,setBag]=useState(false),[pay,setPay]=useState(false),[method,setMethod]=useState("card"),[done,setDone]=useState(false),[seconds,setSeconds]=useState(899),[sellerTab,setSellerTab]=useState("Overview"),[listed,setListed]=useState<P[]>([ps[0],ps[3],ps[5]]),[addOpen,setAddOpen]=useState(false),[dispute,setDispute]=useState(false);
useEffect(()=>{try{setCart(JSON.parse(localStorage.getItem("nx-cart")||"[]"))}catch{}},[]);useEffect(()=>localStorage.setItem("nx-cart",JSON.stringify(cart)),[cart]);useEffect(()=>{if(!pay||method!=="transfer"||done)return;const i=setInterval(()=>setSeconds(s=>Math.max(0,s-1)),1000);return()=>clearInterval(i)},[pay,method,done]);
const shown=useMemo(()=>ps.filter(p=>(cat==="All"||p.cat===cat)&&p.name.toLowerCase().includes(q.toLowerCase())),[q,cat]);const sub=cart.reduce((s,p)=>s+p.price*p.qty,0),fee=Math.round(sub*.015),total=sub+fee;const add=(p:P)=>{setCart(c=>c.some(x=>x.id===p.id)?c.map(x=>x.id===p.id?{...x,qty:x.qty+1}:x):[...c,{...p,qty:1}]);toast.success(p.name+" added to bag")};
if(mode==="seller")return <Seller tab={sellerTab} setTab={setSellerTab} listed={listed} setListed={setListed} addOpen={addOpen} setAddOpen={setAddOpen} dispute={dispute} setDispute={setDispute} back={()=>setMode("shop")}/>;
return <div className="min-h-screen bg-[#f5f5ef]"><Toaster richColors/><div className="bg-black py-2 text-center text-xs font-bold text-white">Free nationwide delivery over ₦150,000 · Secure checkout, every time</div><header><button className="logo">NEXORA<span>.</span></button><nav>{["All","Tech","Sneakers","Home"].map(x=><button onClick={()=>setCat(x)} key={x}>{x==="All"?"New & noteworthy":x}</button>)}</nav><div className="search"><Search/><Input value={q} onChange={e=>setQ(e.target.value)} placeholder="Search pieces, stores, categories"/></div><button className="seller" onClick={()=>setMode("seller")}><Store/> Seller hub</button><button onClick={()=>setAuth(true)}><UserRound/></button><Sheet open={bag} onOpenChange={setBag}><SheetTrigger asChild><button className="bag"><ShoppingBag/><b>{cart.reduce((s,x)=>s+x.qty,0)}</b></button></SheetTrigger><SheetContent className="flex flex-col p-0"><SheetHeader className="border-b p-6"><SheetTitle className="text-2xl font-black">Your bag</SheetTitle></SheetHeader><div className="flex-1 overflow-auto p-6">{cart.length?cart.map(x=><div className="cart" key={x.id}><img src={x.image}/><div><b>{x.name}</b><p>{cash(x.price)}</p><span><button onClick={()=>setCart(c=>c.map(i=>i.id===x.id?{...i,qty:Math.max(1,i.qty-1)}:i))}><Minus/></button>{x.qty}<button onClick={()=>setCart(c=>c.map(i=>i.id===x.id?{...i,qty:i.qty+1}:i))}><Plus/></button><button onClick={()=>setCart(c=>c.filter(i=>i.id!==x.id))}><Trash2/></button></span></div></div>):<p className="empty">Your bag is empty.</p>}</div>{cart.length>0&&<div className="p-6"><div className="total">Subtotal <b>{cash(sub)}</b></div><Button className="cta" onClick={()=>{setBag(false);setPay(true)}}>Secure checkout <LockKeyhole/></Button></div>}</SheetContent></Sheet></header>
<main><section className="feature"><div className="hero"><span>CURATED DROP 07</span><h1>LOUD<br/>BY<br/>DESIGN.</h1><Button onClick={()=>add(ps[0])}>Shop the drop <ArrowRight/></Button><img src={ps[0].image}/></div><div className="side"><button onClick={()=>setCat("Sneakers")}><img src={ps[1].image}/><strong>Sneaker edit <ArrowRight/></strong></button><div><ShieldCheck/><h2>Independent stores. Exceptional finds. One trusted checkout.</h2><button onClick={()=>setMode("seller")}>Open your store →</button></div></div></section>
<section className="catalog"><p className="eyebrow">THE MARKET EDIT</p><div className="catalog-head"><h2>Objects worth owning.</h2><div>{["All","Audio","Sneakers","Tech","Bags","Home"].map(x=><button className={cat===x?"active":""} onClick={()=>setCat(x)} key={x}>{x}</button>)}</div></div><div className="grid">{shown.map(p=><article key={p.id}><div className="photo"><img src={p.image}/>{p.badge&&<i>{p.badge}</i>}<button><Heart/></button><Button onClick={()=>add(p)}>Add to bag <Plus/></Button></div><div className="details"><div><small>{p.seller}</small><h3>{p.name}</h3><p>★ {p.rating} <span>(verified reviews)</span></p></div><b>{cash(p.price)}{p.old&&<del>{cash(p.old)}</del>}</b></div></article>)}</div></section><section className="sell-banner"><div><p className="eyebrow">SELL ON NEXORA</p><h2>Your products deserve a better stage.</h2></div><div><p>List products, collect secure payments, manage delivery and resolve customer issues from one remarkably simple dashboard.</p><Button onClick={()=>setMode("seller")}>Start selling <ArrowRight/></Button></div></section></main>
<Dialog open={auth} onOpenChange={setAuth}><DialogContent className="rounded-[2rem]"><DialogHeader><DialogTitle className="text-3xl font-black">Welcome back</DialogTitle><DialogDescription>One secure account for buying and selling.</DialogDescription></DialogHeader><Tabs defaultValue="buyer"><TabsList className="grid grid-cols-2"><TabsTrigger value="buyer">Buyer</TabsTrigger><TabsTrigger value="seller">Seller</TabsTrigger></TabsList>{["buyer","seller"].map(t=><TabsContent value={t} key={t} className="space-y-4"><Label>Email or phone</Label><Input placeholder="you@example.com"/><Label>Password</Label><Input type="password" placeholder="••••••••"/><button onClick={()=>toast.info("A secure 6-digit code was sent by email/SMS")} className="text-sm font-bold underline">Forgot password?</button><Button className="cta" onClick={()=>{setAuth(false);if(t==="seller")setMode("seller");else toast.success("Signed in securely")}}>Sign in securely</Button><p className="text-center text-sm">New here? <b>Create account</b></p></TabsContent>)}</Tabs></DialogContent></Dialog>
<Checkout open={pay} setOpen={setPay} cart={cart} sub={sub} fee={fee} total={total} method={method} setMethod={setMethod} seconds={seconds} done={done} finish={()=>{setDone(true);setCart([])}}/></div>}
function Checkout({open,setOpen,cart,sub,fee,total,method,setMethod,seconds,done,finish}:any){return <Dialog open={open} onOpenChange={setOpen}><DialogContent className="max-h-[92vh] overflow-auto rounded-[2rem] sm:max-w-3xl"><DialogHeader><DialogTitle className="text-3xl font-black">Secure checkout</DialogTitle><DialogDescription>Buyer protection holds payment until delivery is confirmed.</DialogDescription></DialogHeader>{done?<div className="success"><i><Check/></i><h2>Order confirmed</h2><p>Order NX-48291 is protected by Nexora.</p><Button onClick={()=>setOpen(false)}>Continue shopping</Button></div>:<div className="checkout"><div><div className="pay-tabs"><button className={method==="card"?"active":""} onClick={()=>setMethod("card")}><CreditCard/> Card</button><button className={method==="transfer"?"active":""} onClick={()=>setMethod("transfer")}><CircleDollarSign/> Bank transfer</button></div>{method==="card"?<div className="form"><Label>Card number</Label><Input placeholder="0000 0000 0000 0000"/><div><Input placeholder="MM / YY"/><Input placeholder="CVV"/></div><Label>Name on card</Label><Input placeholder="Full name"/><Button onClick={finish}>Pay {cash(total)} securely <LockKeyhole/></Button><small>Demo checkout. Connect Paystack or Flutterwave before live use.</small></div>:<div className="transfer"><span>RESERVED ACCOUNT <b><Clock3/>{String(Math.floor(seconds/60)).padStart(2,"0")}:{String(seconds%60).padStart(2,"0")}</b></span><small>NEXORA / PROVIDUS BANK</small><h2>0912 847 366</h2><p>Pay exactly <b>{cash(total)}</b></p><Button onClick={finish}>I completed the transfer</Button></div>}</div><aside><h3>Order summary</h3>{cart.map((x:C)=><p key={x.id}>{x.name} × {x.qty}<b>{cash(x.price*x.qty)}</b></p>)}<hr/><p>Subtotal <b>{cash(sub)}</b></p><p>Protection fee <b>{cash(fee)}</b></p><p className="grand">Total <b>{cash(total)}</b></p></aside></div>}</DialogContent></Dialog>}
function Seller({tab,setTab,listed,setListed,addOpen,setAddOpen,dispute,setDispute,back}:any){const nav=[["Overview",LayoutDashboard],["Products",Package],["Orders",ShoppingBag],["Payments",WalletCards],["Disputes",MessageSquareWarning],["Settings",Settings]];return <div className="dashboard"><Toaster richColors/><aside><button className="logo" onClick={back}>NEXORA<span>.</span></button><div className="store-id"><b>A</b><span>Atelier Lagos<small>Verified store</small></span></div><nav>{nav.map(([x,I]:any)=><button className={tab===x?"active":""} onClick={()=>setTab(x)} key={x}><I/>{x}{x==="Disputes"&&<i>1</i>}</button>)}</nav><button onClick={back}><Store/> View marketplace</button></aside><section><header><Bell/><b>Olawumi Steven</b><i>OS</i></header><main><p className="eyebrow">SELLER COMMAND CENTRE</p><div className="seller-title"><h1>{tab}</h1>{tab==="Products"&&<Button onClick={()=>setAddOpen(true)}><Plus/> Add product</Button>}</div>{tab==="Overview"&&<Overview/>}{tab==="Products"&&<ProductTable list={listed} remove={(id:number)=>setListed(listed.filter((x:P)=>x.id!==id))}/>} {tab==="Orders"&&<Rows/>}{tab==="Payments"&&<Payments/>}{tab==="Disputes"&&<Disputes open={()=>setDispute(true)}/>} {tab==="Settings"&&<SettingsPanel/>}</main></section><NewProduct open={addOpen} close={()=>setAddOpen(false)} add={(p:P)=>setListed([...listed,p])}/><Dialog open={dispute} onOpenChange={setDispute}><DialogContent><DialogHeader><DialogTitle>Dispute DIS-1094</DialogTitle><DialogDescription>Buyer reports a damaged buckle.</DialogDescription></DialogHeader><Textarea placeholder="Explain what happened and propose a resolution…"/><Button onClick={()=>{setDispute(false);toast.success("Response sent to resolution team")}}>Send response</Button></DialogContent></Dialog></div>}
function Overview(){return <><div className="metrics">{[["Gross sales","₦2,840,500",CircleDollarSign],["Orders","186",ShoppingBag],["Store views","14,892",Eye],["Conversion","4.26%",TrendingUp]].map(([a,b,I]:any)=><div><I/><small>{a}</small><b>{b}</b><em>+18.4% this month</em></div>)}</div><div className="panel chart"><h3>Revenue performance</h3><div>{[42,62,48,78,65,92,84].map((h,i)=><i style={{height:h+"%"}} key={i}/>)}</div></div></>}
function ProductTable({list,remove}:any){return <div className="panel table"><h3>Your live catalog</h3>{list.map((p:P)=><div key={p.id}><img src={p.image}/><b>{p.name}<small>Live · {p.stock} in stock</small></b><span>{cash(p.price)}</span><button onClick={()=>remove(p.id)}><Trash2/></button></div>)}</div>}
function Rows(){return <div className="panel table">{[["NX-48291","Auralis Studio Max","₦189,000","Processing"],["NX-48283","No. 12 Weekender","₦128,000","Shipped"],["NX-48276","Sora Lounge Chair","₦214,000","Delivered"]].map(x=><div><b>{x[0]}<small>{x[1]}</small></b><span>{x[2]}</span><em>{x[3]}</em></div>)}</div>}
function Payments(){return <div className="payment-panels"><div><small>Available balance</small><h2>₦842,500</h2><p>Next payout: September 8</p><Button onClick={()=>toast.success("Payout requested")}>Request payout</Button></div><div className="panel"><ShieldCheck/><h3>Settlement account</h3><p>GTBANK •••• 2471<br/><b>OLAWUMI STEVEN</b></p><Button variant="outline">Change payment method</Button></div></div>}
function Disputes({open}:any){return <div className="panel dispute"><MessageSquareWarning/><div><b>DIS-1094 · Response due in 18h</b><p>Buyer reports the received bag has a damaged buckle.</p></div><Button onClick={open}>Review case</Button></div>}
function SettingsPanel(){return <div className="panel form"><h3>Store profile</h3><Label>Store name</Label><Input defaultValue="Atelier Lagos"/><Label>Support email</Label><Input defaultValue="hello@atelierlagos.com"/><Label>Description</Label><Textarea defaultValue="Considered essentials, made to travel well."/><Button onClick={()=>toast.success("Store saved")}>Save changes</Button></div>}
function NewProduct({open,close,add}:any){const[name,setName]=useState(""),[price,setPrice]=useState("");return <Dialog open={open} onOpenChange={close}><DialogContent><DialogHeader><DialogTitle>List a new product</DialogTitle><DialogDescription>Add clear details for confident buyers.</DialogDescription></DialogHeader><label className="upload"><Upload/>Upload product photos<input type="file" hidden/></label><Label>Product name</Label><Input value={name} onChange={e=>setName(e.target.value)}/><Label>Price (₦)</Label><Input type="number" value={price} onChange={e=>setPrice(e.target.value)}/><Textarea placeholder="Materials, dimensions, delivery details…"/><Button onClick={()=>{if(!name||!price)return toast.error("Add a name and price");add({...ps[1],id:Date.now(),name,price:Number(price),seller:"Atelier Lagos"});close();toast.success("Product published")}}>Publish product</Button></DialogContent></Dialog>}
