"use client";
import {useState} from "react";
import {ArrowRight,Check,ShoppingBag,Store} from "lucide-react";
import {Button} from "@/components/ui/button";
import {Dialog,DialogContent,DialogDescription,DialogHeader,DialogTitle} from "@/components/ui/dialog";
import {Input} from "@/components/ui/input";
import {Label} from "@/components/ui/label";
import {toast} from "sonner";

export default function Signup({open,setOpen,onSeller}:{open:boolean;setOpen:(v:boolean)=>void;onSeller:()=>void}){
 const[role,setRole]=useState<"buyer"|"seller">("buyer"),[name,setName]=useState(""),[email,setEmail]=useState(""),[password,setPassword]=useState(""),[confirm,setConfirm]=useState(""),[storeName,setStoreName]=useState(""),[agreed,setAgreed]=useState(false),[created,setCreated]=useState(false);
 const submit=()=>{if(!name||!email||!password)return toast.error("Complete all required fields");if(password.length<8)return toast.error("Password must contain at least 8 characters");if(password!==confirm)return toast.error("Your passwords do not match");if(role==="seller"&&!storeName)return toast.error("Enter your store name");if(!agreed)return toast.error("Accept the terms to create your account");setCreated(true)};
 const close=(v:boolean)=>{setOpen(v);if(!v)setTimeout(()=>setCreated(false),200)};
 return <Dialog open={open} onOpenChange={close}><DialogContent className="max-h-[92vh] overflow-y-auto rounded-[2rem] sm:max-w-xl">{created?<div className="success"><i><Check/></i><h2>Welcome to Zunavoa</h2><p>Your {role} account has been created successfully.</p><Button onClick={()=>{if(role==="seller")onSeller();else{setOpen(false);toast.success("Buyer account ready — start shopping")}}}>{role==="seller"?"Set up my store":"Start shopping"} <ArrowRight/></Button></div>:<><DialogHeader><DialogTitle className="text-3xl font-black">Create your account</DialogTitle><DialogDescription>First, choose how you want to use Zunavoa.</DialogDescription></DialogHeader><div className="signup-role"><button type="button" className={role==="buyer"?"active":""} onClick={()=>setRole("buyer")}><ShoppingBag/><b>Join as a buyer</b><small>Shop products and track orders</small></button><button type="button" className={role==="seller"?"active":""} onClick={()=>setRole("seller")}><Store/><b>Join as a seller</b><small>Open a store and list products</small></button></div><div className="signup-form"><Label htmlFor="signup-name">Full name</Label><Input id="signup-name" value={name} onChange={e=>setName(e.target.value)} placeholder="Your full name"/><Label htmlFor="signup-email">Email address</Label><Input id="signup-email" type="email" value={email} onChange={e=>setEmail(e.target.value)} placeholder="you@example.com"/>{role==="seller"&&<><Label htmlFor="store-name">Store name</Label><Input id="store-name" value={storeName} onChange={e=>setStoreName(e.target.value)} placeholder="Your business or store name"/></>}<div className="signup-passwords"><div><Label htmlFor="signup-password">Password</Label><Input id="signup-password" type="password" value={password} onChange={e=>setPassword(e.target.value)} placeholder="At least 8 characters"/></div><div><Label htmlFor="confirm-password">Confirm password</Label><Input id="confirm-password" type="password" value={confirm} onChange={e=>setConfirm(e.target.value)} placeholder="Repeat password"/></div></div><label className="terms"><input type="checkbox" checked={agreed} onChange={e=>setAgreed(e.target.checked)}/><span>I agree to the Terms, Privacy Policy and {role==="seller"?"Seller Agreement":"Buyer Protection policy"}.</span></label><Button className="cta" onClick={submit}>Create {role} account <ArrowRight/></Button><p className="text-center text-sm">Already registered? <button type="button" className="font-black underline" onClick={()=>setOpen(false)}>Sign in</button></p></div></>}</DialogContent></Dialog>
}
